# Generated by Django 4.0.3 on 2022-03-08 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bienesmodel_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienesmodel',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
